package com.medworld.appdoctor;

import com.medworld.appdoctor.R.drawable;

import android.annotation.SuppressLint;
import android.app.ActionBar;
import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.view.MenuItem;
import android.widget.TextView;

public class ResultEvaluate extends Activity {
    TextView tv1,tv2,tvU;
    int position;
	@SuppressLint("NewApi")
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.result_evaluate);
		tvU=(TextView)findViewById(R.id.update1);
		tv1=(TextView)findViewById(R.id.result);
		tv2=(TextView)findViewById(R.id.note);
		tv2.setTextColor(Color.argb(240, 240, 0, 0));
		tvU.setTextColor(Color.argb(220, 69, 26, 104));
		
		tv2.setText("NOTE: SYMPTOM CHECKER SHOWS ONLY A ROUGH PREDICTION OF YOUR DISEASE. ALWAYS CONSULT A DOCTOR BEFORE TAKING FURTHER ACTIONS!");
		tv1.setTextColor(Color.argb(240, 83, 166, 0));
		if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.JELLY_BEAN_MR2) 
		{
			ActionBar actionbar=getActionBar();
			actionbar.setDisplayHomeAsUpEnabled(true);
			actionbar.setHomeAsUpIndicator(drawable.action_previous);
		}
		
		Intent i=getIntent();
		position=i.getIntExtra("code", position);
		
		switch(position)
		  {
		     case 1: tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •cholera\n  •influenza\n•  typhoid fever\nconsult a doctor for more accurate results!");	
		             break;
		     case 2:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •diphtheria\nconsult a doctor for more accurate results!");
		             break;
		     case 3:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •measels\nconsult a doctor for more accurate results!");
		             break;
		     case 4:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •scarlet fever\nconsult a doctor for more accurate results!");
		             break;
		     case 5:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •scurvy\nconsult a doctor for more accurate results!");
		             break;
		     case 6:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •smallpox\nconsult a doctor for more accurate results!");
		             break;
		     case 7:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •yellow fever\nconsult a doctor for more accurate results!");
		             break;
		     case 8:tvU.setText("Symptom checker matched a disease based on your input!\n");
		            tv1.setText("You are probably having\n  •chickenpox(vericella)\nconsult a doctor for more accurate results!");
		             break;
		     case 9: tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •jaundice\n  •yellowfever\n  •prostate cancer\n  •bladder cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 10:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •jaundice\n  •yellowfever\nconsult a doctor for more accurate results!");
		             break;
		     case 11:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •nephritis\n  •bladder cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 12:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •chickenpox(vericella)\n  •melanoma(skin cancer)\nconsult a doctor for more accurate results!");
		             break;
		     case 13:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n •tuberculosis(TB)\n  •lung cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 14:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •meningitis\nconsult a doctor for more accurate results!");
		             break;
		     case 15:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •stroke\nconsult a doctor for more accurate results!");
		             break;
		     case 16:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •cardiomyopathy\nconsult a doctor for more accurate results!");
		             break;
		     case 17:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •Transient Ischalmic Attack(TIA)\nconsult a doctor for more accurate results!");
		             break;
		     case 18:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •vascular dimentia\nconsult a doctor for more accurate results!");
		             break;
		     case 19:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		    	     tv1.setText("You are probably having any of these diseases:\n  •Transient Ischalmic Attack(TIA)\n  •Brain cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 20:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •bronchopneumonia\n  •arrhythmia\n  •congential heart disease\n  •heart attack\nconsult a doctor for more accurate results!");
		             break;
		     case 21:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •scurvy\nconsult a doctor for more accurate results!");
		             break;
		     case 22:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •Transient Ischalmic Attack(TIA)\n  •Stroke\nconsult a doctor for more accurate results!");
		             break;
		     case 23:tv1.setText("Your choices does not match any major diseases.You are probably just fine!\nconsult a doctor for more accurate results!");
		             break;
		     case 24:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •cholera\nconsult a doctor for more accurate results!");
		             break;
		     case 25:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •diphtheria\nconsult a doctor for more accurate results!");
		             break;
		     case 26:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •malaria\nconsult a doctor for more accurate results!");
		             break;
		     case 27:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •measels\nconsult a doctor for more accurate results!");
		             break;
		     case 28:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •mumps\nconsult a doctor for more accurate results!");
		             break;
		     case 29:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •influenza\nconsult a doctor for more accurate results!");
		             break;
		     case 30:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •poliomyelitis\nconsult a doctor for more accurate results!");
		             break;
		     case 31:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •scarlet fever\nconsult a doctor for more accurate results!");
		             break;
		     case 32:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •scurvy\nconsult a doctor for more accurate results!");
		             break;
		     case 33:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •smallpox\nconsult a doctor for more accurate results!");
		             break;
		     case 34:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •typhoid fever\nconsult a doctor for more accurate results!");
		             break;
		     case 35:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •yellow fever\nconsult a doctor for more accurate results!");
		             break;
		     case 36:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •dengue fever\nconsult a doctor for more accurate results!");
		             break;
		     case 37:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •chickenpox(vericella)\nconsult a doctor for more accurate results!");
		             break;
		     case 38:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •leptospirosis(field fever)\nconsult a doctor for more accurate results!");
		             break;
		     case 39:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •jaundice\nconsult a doctor for more accurate results!");
		             break;
		     case 40:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •bronchopneumonia\nconsult a doctor for more accurate results!");
		             break;
		     case 41:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •tuberculosis(TB)\nconsult a doctor for more accurate results!");
		             break;
		     case 42:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •whooping cough\nconsult a doctor for more accurate results!");
		             break;
		     case 43:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •angina pectoris\nconsult a doctor for more accurate results!");
		             break;
		     case 44:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •asthma\nconsult a doctor for more accurate results!");
		             break;
		     case 45:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •meningitis\nconsult a doctor for more accurate results!");
		             break;
		     case 46:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •nephritis\nconsult a doctor for more accurate results!");
		             break;
		     case 47:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •lung cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 48:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •brain cancer\nconsult a doctor for more accurate results!");
		             break;
		     case 49:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •leukemia\nconsult a doctor for more accurate results!");
		             break;
		     case 50:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •melanoma(skin cancer)\nconsult a doctor for more accurate results!");
                     break; 
		     case 51:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •prostate cancer\nconsult a doctor for more accurate results!");
                     break; 
		     case 52:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •bladder cancer\nconsult a doctor for more accurate results!");
                     break; 
		     case 53:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •heart attack\nconsult a doctor for more accurate results!");
                     break; 
		     case 54:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •arrhythmia\nconsult a doctor for more accurate results!");
                     break; 
		     case 55:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •congential heart disease\nconsult a doctor for more accurate results!");
                     break; 
		     case 56:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •stroke\nconsult a doctor for more accurate results!");
                     break; 
		     case 57:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •cardiomyopathy\nconsult a doctor for more accurate results!");
                     break; 
		     case 58:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •aortic aneurysm\nconsult a doctor for more accurate results!");
                     break; 
		     case 59:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •Transient Ischalmic Attack(TIA)\nconsult a doctor for more accurate results!");
                     break; 
		     case 60:tvU.setText("Symptom checker matched a disease based on your input!\n");
		             tv1.setText("You are probably having\n  •vascular dimentia\nconsult a doctor for more accurate results!");
                     break; 
		     case 61:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •diphtheria\n  •malaria\n  •influenza\n  •leptospirosis(field fever)\n  •smallpox\nconsult a doctor for more accurate results!");
                     break;
		     case 62:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •malaria\nconsult a doctor for more accurate results!");
                     break;
		     case 63:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •cholera\n  •malaria\n  •influenza\n  •poliomyelitis\n  •leptospirosis(field fever)\nconsult a doctor for more accurate results!");
                     break;
		     case 64:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •cholera\n  •poliomyelitis\n  •vascular dimentia\nconsult a doctor for more accurate results!");
                     break;
		     case 65:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •diphtheria\n  •influenza\n  •whooping cough\nconsult a doctor for more accurate results!");
                     break;
		     case 66:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •measels\n  •influenza\n  •whooping cough\nconsult a doctor for more accurate results!");
                     break;
		     case 67:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •scurvy\n  •melanoma(skin cancer)\nconsult a doctor for more accurate results!");
                     break;
		     case 68:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •arrhythmia\n  •stroke\n  •cardiomyopathy\n  •vascular dimentia\nconsult a doctor for more accurate results!");
                     break;
		     case 69:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •leptospirosis(field fever)\n  •tuberculosis(TB)\n  •leukemia\n  •chickenpox(vericella)\nconsult a doctor for more accurate results!");
                     break;
		     case 70:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •poliomyelitis\n  •meningitis\n  •leukemia\n  •cardiomyopathy\nconsult a doctor for more accurate results!");
                     break;
		     case 71:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
		             tv1.setText("You are probably having any of these diseases:\n  •arrhtthmia\n  •congential heart disease\n  •cardiomyopathy\n  •aortic aneurysm\nconsult a doctor for more accurate results!");
                     break;
             case 72:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •arrhythmia\n  •cardiomyopathy\n  •heart attack\nconsult a doctor for more accurate results!");
                     break;
             case 73:tvU.setText("Symptom checker matched a disease based on your input!\n");
                     tv1.setText("You are probably having\n  •vascular dimentia\nconsult a doctor for more accurate results!");
                     break;
             case 74:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •arrhythmia\n  •congential heart disease\nconsult a doctor for more accurate results!");
                     break;
             case 75:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •arrhythmia\n  •congential heart disease\n  •asthma\n  •angina pectoris\n  •bronchopneumonia\n  •tuberculosis(TB)\nconsult a doctor for more accurate results!");
                     break;
             case 76:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •measels\n  •poliomyelitis\n  •typhoid fever\n  •bronchopneumonia\n  •tuberculosis(TB)\n  •angina pectoris\nconsult a doctor for more accurate results!");
                     break;
             case 77:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •scurvy\n  •melanoma(skin cancer)\nconsult a doctor for more accurate results!");
                     break;  
             case 78:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •poliomyelitis\n  •aortic aneurysm\n  •bladder cancer\nconsult a doctor for more accurate results!");
                     break;
             case 79:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •poliomyelitis\n  •meningitis\n  •peripheral artery disease\nconsult a doctor for more accurate results!");
                     break;
             case 80:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •diphtheria\n  •mumps\n  •aortic aneurysm\nconsult a doctor for more accurate results!");
                     break;
             case 81:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •meningitis\n  •leukemia\nconsult a doctor for more accurate results!");
                     break;
             case 82:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •smallpox\n  •melanoma(skin cancer)\nconsult a doctor for more accurate results!");
                     break;
             case 83:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •diphtheria\n  •bronchopneumonia\n  •asthma\n  •tuberculosis(TB)\n  •aortic aneurysm\nconsult a doctor for more accurate results!");
                     break;
             case 84:tvU.setText("Symptom checker matched a disease based on your input!\n");
                     tv1.setText("You are probably having\n  •cholera\nconsult a doctor for more accurate results!");
                     break;
             case 85:tvU.setText("Symptom checker matched a list of diseases based on your input!\n");
                     tv1.setText("You are probably having any of these diseases:\n  •Transient Ischalmic Attack(TIA)\nconsult a doctor for more accurate results!");
                     break;
             case 86:tv1.setText("Sorry we could not match any disease with your symptoms.Consult a doctor for a proper checkup!");              
		             break;
             case 87:tv1.setText("Sorry you have too many symptoms to match a particular disease.Immediately consult a doctor for a checkup!");        
		  }
	}
	
	public boolean onOptionsItemSelected(MenuItem item) {
	    switch (item.getItemId()) {
	        case android.R.id.home:
	            // app icon in action bar clicked; goto parent activity.
	            this.finish();
	            return true;
	        default:
	            return super.onOptionsItemSelected(item);
	    }

    }

}
